# Generated by Django 4.1 on 2022-10-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hungry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='specialization',
            field=models.CharField(default='Caffe', max_length=128),
        ),
        migrations.AddField(
            model_name='price',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='place',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='userphoto/'),
        ),
    ]
