# Generated by Django 4.1 on 2022-10-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hungry', '0002_place_specialization_price_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='good',
        ),
        migrations.AddField(
            model_name='good',
            name='price',
            field=models.ManyToManyField(blank=True, related_name='goods', to='hungry.price'),
        ),
        migrations.AlterField(
            model_name='place',
            name='specialization',
            field=models.CharField(max_length=128),
        ),
    ]
