# Generated by Django 4.1 on 2022-10-12 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hungry', '0006_good_cls'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='place',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='hungry.place'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='good',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.FloatField(),
        ),
    ]
