# Generated by Django 4.1 on 2022-10-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hungry', '0007_good_place_good_rating_alter_price_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
