# Generated by Django 4.1 on 2022-10-14 08:34

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hungry', '0008_good_price_delete_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddon',
            name='address',
            field=django_google_maps.fields.AddressField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='useraddon',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
    ]
