# Generated by Django 4.1 on 2022-10-14 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hungry', '0009_useraddon_address_useraddon_geolocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddon',
            name='geolocation',
        ),
    ]
