# Generated by Django 4.1 on 2022-10-14 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hungry', '0010_remove_useraddon_geolocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='place',
            name='specialization',
        ),
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='hungry.category'),
        ),
        migrations.AlterField(
            model_name='place',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed', to=settings.AUTH_USER_MODEL),
        ),
    ]
