# Generated by Django 4.1 on 2022-10-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hungry', '0011_remove_place_rating_remove_place_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='description',
            field=models.FileField(blank=True, null=True, upload_to='desc/'),
        ),
    ]
