# Generated by Django 4.1 on 2022-10-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hungry', '0013_alter_good_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_pic',
            field=models.ImageField(blank=True, null=True, upload_to='categorypics/'),
        ),
    ]
