# Generated by Django 4.1 on 2022-10-15 10:30

from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hungry', '0014_category_cat_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Userphoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, upload_to='userphotos/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userphotos', to='hungry.place')),
            ],
        ),
    ]
