# Generated by Django 4.1 on 2022-10-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hungry', '0015_alter_place_geolocation_userphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='cls',
            field=models.CharField(max_length=128),
        ),
    ]
