# Generated by Django 4.1 on 2022-10-16 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hungry', '0017_remove_place_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='visitors',
            field=models.ManyToManyField(blank=True, related_name='visited', to=settings.AUTH_USER_MODEL),
        ),
    ]
