# Generated by Django 4.1 on 2022-10-17 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hungry', '0018_place_visitors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='rating',
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='hungry.good')),
            ],
        ),
    ]
