# Generated by Django 4.1 on 2022-10-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hungry', '0019_remove_good_rating_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
