# Generated by Django 4.1 on 2022-10-17 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hungry', '0022_remove_rate_rated_by_rate_rated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='rated_by',
        ),
        migrations.AddField(
            model_name='rate',
            name='rated_by',
            field=models.ManyToManyField(blank=True, related_name='rated', to=settings.AUTH_USER_MODEL),
        ),
    ]
