# Generated by Django 4.1 on 2022-10-17 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hungry', '0024_remove_rate_rated_by_rate_rated_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='rated_by',
            new_name='user',
        ),
    ]
