# Generated by Django 4.1 on 2022-10-17 20:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hungry', '0027_remove_rate_user_rate_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='user',
        ),
        migrations.AddField(
            model_name='good',
            name='rated_by',
            field=models.ManyToManyField(blank=True, related_name='rated', to=settings.AUTH_USER_MODEL),
        ),
    ]
