# Generated by Django 4.1 on 2022-10-18 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hungry', '0029_rate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed', to=settings.AUTH_USER_MODEL),
        ),
    ]
